// Generated by CoffeeScript 1.6.2
(function() {
  var path;

  path = require('path');

  module.exports = {
    dirname: process.cwd() || __dirname,
    dirs: [process.cwd(), __dirname, path.join(__dirname, '..')],
    port: 3000,
    debug: false,
    cookie_secret: null,
    session_secret: null,
    session: true,
    cookie: true,
    stylus: true,
    connect_assets: true,
    hogan: true,
    less: false,
    compress: true,
    cache: true,
    viewEngine: 'jade',
    staticMaxAge: 86400,
    newRelic: {
      license_key: null,
      app_name: null,
      logging: {
        level: 'trace'
      }
    },
    locals: {
      title: '',
      site_name: 'Tapas',
      description: "",
      css_libraries: [],
      js_libraries: [],
      use: {
        fontawesome: true,
        bootstrap: {
          responsive: false,
          navbar: {
            fixed: false
          },
          fixedNavbar: false,
          fluid: false,
          collapsibleNavbar: false
        },
        user: {
          navbar: false
        },
        jquery: true,
        angular: true
      },
      menus: {
        navbar: {
          '/': {
            title: 'Home'
          }
        },
        primary: {
          '/': {
            title: 'Home'
          },
          '/login': {
            title: 'Login'
          },
          '/register': {
            title: 'Register'
          },
          '/logout': {
            title: 'Logout'
          }
        }
      },
      regions: {
        footer: {
          'copyright': '<p>Copyright 2012</p>',
          'backToTop': '<p class="pull-right"><a href="#">Back to top</a></p>'
        }
      },
      grid: {
        size: 12,
        content: 12,
        left: 3,
        right: 3
      },
      classes: {
        content: [],
        left: [],
        right: []
      }
    },
    viewOptions: {
      layout: false,
      pretty: false,
      complexNames: true
    },
    ksAppConfigure: true
  };

}).call(this);
